### ISSUE TITLE
Nebulosa theme

### ISSUE THREAD

**Issue by agaonsindhe** [uni-linux/recipes#1]
Hi Dalton,

First of all your work is brilliant, I am so glad to have found your themes/work.
Since I am a beginner in ubuntu, and I an hour ago installed Nebulosa theme as per your instructions and it worked fine, but the problem I am now facing is I cannot see anything in the dock now and also the search thing which comes by default with Ubuntu seems to be gone now.
Every time I have to open an application, I need to type in a equivalent terminal command to open that.
I hope my message is conveyed to you, waiting for an solution.

Regards,
Newbie Ubuntu

**Comment by daltonmenezes** [comment]
Hi @AnshuKopite . Thank you so much.
Have you tried to press windows button on keyboard? I believe this works to open the launcher and then you can open your programs e pin it on plank dock.

**Comment by agaonsindhe** [comment]
Hi Dalton,
Thanks unfortunately missed pressing windows.
Go t what i wanted. Is there something like dock settings sort of thing.

**Comment by daltonmenezes** [comment]
I'm sorry. It's unclear to me. Can you give me more details about what you need?

**Comment by agaonsindhe** [comment]
HI Dalton,

Leave it gotta explore somethings by my own, cant expect spoon feeding every time, windows worked for me, and Alt + F1 gave me the launcher.
 Thank you very much for the prompt response and help. :) :1st_place_medal: See ya soon.
