### ISSUE TITLE
dissapearing bottom app menu

### ISSUE THREAD

**Issue by Amirrkhan** [uni-linux/recipes#2]
First of all I'd like to say thanks for your work, it's really good!
My problem is that always after rebooting system, the bottom app menu dissapears, and everytime I need to reinstall theme.
Is there some way to fix it?

**Comment by daltonmenezes** [comment]
Hi @Amirrkhan . Please, open `gnome-session-properties`. Then, click on 'Add' button and type 'plank' as the name and 'plank' as the command. Then, click on 'Add' button and try to reboot the system.

**Comment by Amirrkhan** [comment]
It works, thks
